# Generated by Django 3.2.12 on 2022-03-17 10:37

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='رقم الأية')),
                ('text', models.CharField(max_length=100000, verbose_name='النص')),
                ('text_without_tashkil', models.CharField(max_length=100000, verbose_name='النص بدون تشكيل')),
            ],
            options={
                'verbose_name': ' الأيات',
                'verbose_name_plural': ' الأيات',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('page_count', models.IntegerField(blank=True, null=True, verbose_name='عدد الصفحات')),
                ('type', models.CharField(choices=[('book', 'كتاب'), ('artical', 'مقال')], max_length=10, verbose_name='نوع')),
                ('status', models.CharField(choices=[('p', 'منشور'), ('n', 'غير منشور')], default='p', max_length=1, verbose_name='حالة النشر')),
                ('cover', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_covers', to=settings.FILER_IMAGE_MODEL, verbose_name='الصوره')),
                ('file', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.file', verbose_name='الملف')),
            ],
            options={
                'verbose_name': 'الكتب والمقالات',
                'verbose_name_plural': 'الكتب والمقالات',
            },
        ),
        migrations.CreateModel(
            name='BookInAlSaheh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الكتاب')),
                ('name_without_tashkil', models.CharField(max_length=100, verbose_name='without tashkel العنوان')),
            ],
            options={
                'verbose_name': 'الكتب/صحيح البخاري',
                'verbose_name_plural': 'الكتب/صحيح البخاري',
            },
        ),
        migrations.CreateModel(
            name='CallUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الالكتروني')),
                ('message', models.CharField(max_length=1000, verbose_name='الرسالة')),
            ],
            options={
                'verbose_name': 'التواصل معنا',
                'verbose_name_plural': 'التواصل معنا',
            },
        ),
        migrations.CreateModel(
            name='ChapterInAlSaheh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='أسم الباب')),
                ('name_without_tashkil', models.CharField(max_length=100, verbose_name='without tashkel العنوان')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bookinalsaheh', verbose_name='كتاب في صحيح البخاري')),
            ],
            options={
                'verbose_name': 'الباب/صحيح البخاري',
                'verbose_name_plural': 'الباب/صحيح البخاري',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='البريد الالكتروني')),
            ],
            options={
                'verbose_name': 'البريد الالكتروني',
                'verbose_name_plural': 'البريد الالكتروني',
            },
        ),
        migrations.CreateModel(
            name='Hadith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100000, verbose_name='النص')),
                ('text_without_tashkil', models.CharField(max_length=100000, verbose_name='النص بدون تشكيل')),
                ('number', models.IntegerField(verbose_name='Hadith الترتيب ')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bookinalsaheh', verbose_name='كتاب في صحيح البخاري')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.chapterinalsaheh', verbose_name='الباب/صحيح البخاري')),
            ],
            options={
                'verbose_name': 'الحديث في صحيح البخاري',
                'verbose_name_plural': 'الحديث في صحيح البخاري',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='OtherScienceSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(max_length=300, verbose_name='مواضيع')),
                ('file_type', models.CharField(choices=[('video', 'فيديو'), ('audio', 'ملف صوتي')], max_length=12, verbose_name='نوع الملف')),
                ('status', models.CharField(choices=[('p', 'منشور'), ('n', 'غير منشور')], default='p', max_length=1, verbose_name='حالة النشر')),
            ],
            options={
                'verbose_name': 'مواضيع العلوم الأخري',
                'verbose_name_plural': 'مواضيع العلوم الأخري',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
            ],
            options={
                'verbose_name': 'أرقام الهاتف',
                'verbose_name_plural': 'أرقام الهاتف',
            },
        ),
        migrations.CreateModel(
            name='PrayTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fajr', models.TimeField(null=True, verbose_name='الفجر')),
                ('Sunrise', models.TimeField(null=True, verbose_name='الشروق')),
                ('Dhuhr', models.TimeField(null=True, verbose_name='الظهر')),
                ('Asr', models.TimeField(null=True, verbose_name='العصر')),
                ('Maghrib', models.TimeField(null=True, verbose_name='المغرب')),
                ('Isha', models.TimeField(null=True, verbose_name='العشاء')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='المدينة')),
                ('country', models.CharField(max_length=50, null=True, verbose_name='الدولة')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('hijri', models.CharField(blank=True, max_length=20, null=True, verbose_name='hijri')),
            ],
            options={
                'verbose_name': 'مواقيت الصلاة',
                'verbose_name_plural': 'مواقيت الصلاة',
            },
        ),
        migrations.CreateModel(
            name='RelatedSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.URLField(verbose_name='الموقع')),
                ('name', models.CharField(blank=True, max_length=80, null=True, verbose_name='الاسم')),
                ('text', models.CharField(blank=True, max_length=10000, null=True, verbose_name='كلمات بسيطة')),
            ],
            options={
                'verbose_name': 'مواقع ذات صلة',
                'verbose_name_plural': 'مواقع ذات صلة',
            },
        ),
        migrations.CreateModel(
            name='Sura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Makkah', 'مكة'), ('Medina', 'المدينة')], max_length=50, null=True, verbose_name='مكان التنزيل')),
                ('number', models.IntegerField(verbose_name='رقم')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم')),
                ('ayas_count', models.IntegerField(null=True, verbose_name='عدد الأيات')),
            ],
            options={
                'verbose_name': 'تفسير القرآن والتلاوة',
                'verbose_name_plural': 'السورة',
            },
        ),
        migrations.CreateModel(
            name='TafsirHadithInAlSaheh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100000, null=True, verbose_name='نص شرح الحديث')),
                ('video_url', models.URLField(max_length=400, verbose_name='رابط الفيديو ')),
                ('status', models.CharField(choices=[('p', 'منشور'), ('n', 'غير منشور')], default='p', max_length=1, verbose_name='حالة النشر')),
                ('audio_tafsir', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_hadith_file', to='filer.file', verbose_name='الشرح الصوتي')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bookinalsaheh', verbose_name='كتاب في صحيح البخاري')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.chapterinalsaheh', verbose_name='الباب/صحيح البخاري')),
                ('hadith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.hadith', verbose_name='الحديث')),
                ('video_tafsir', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TafsirHadithInAlSahehvideo_tafsir_file', to='filer.file', verbose_name='التفسير المرئي')),
            ],
            options={
                'verbose_name': 'الحديث الشريف',
                'verbose_name_plural': 'الحديث الشريف',
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('type', models.CharField(choices=[('quran', 'القرآن الكريم'), ('hadith', 'الحديث'), ('OtherScience', 'العلوم الأخري')], max_length=20, verbose_name='نوع')),
                ('video_url', models.URLField(verbose_name='رابط يوتيوب')),
                ('status', models.CharField(choices=[('p', 'منشور'), ('n', 'غير منشور')], default='p', max_length=1, verbose_name='حالة النشر')),
                ('file', filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, to='filer.file', verbose_name='المحتوي')),
            ],
            options={
                'verbose_name': 'المجالس',
                'verbose_name_plural': 'مجالس',
            },
        ),
        migrations.CreateModel(
            name='OtherScience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('status', models.CharField(choices=[('p', 'منشور'), ('n', 'غير منشور')], default='p', max_length=1, verbose_name='حالة النشر')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='رابط يوتيوب')),
                ('file', filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, to='filer.file', verbose_name='محتوي')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.othersciencesubject', verbose_name='مواضيع العلوم الأخري')),
            ],
            options={
                'verbose_name': 'العلوم الأخري',
                'verbose_name_plural': 'العلوم الأخري',
            },
        ),
        migrations.CreateModel(
            name='General_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_link', models.URLField(verbose_name='رابط الانسجرام')),
                ('facebook_link', models.URLField(verbose_name='رابط الفيسبوك')),
                ('twitter_link', models.URLField(verbose_name='رابط تويتر')),
                ('youtube_link', models.URLField(verbose_name='رابط يوتيوب')),
                ('about_sheikh_short', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='نبذة مختصرة عن الشيخ')),
                ('about_mousa_short', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='نبذة مخصترة عن الجمعية ')),
                ('about_sheikh', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name=' عن الشيخ')),
                ('about_mousa', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='عن الجمعية')),
                ('privacy_policy', models.CharField(blank=True, max_length=50000, null=True, verbose_name='سياسة الخصوصية')),
                ('cover_page', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_page', to=settings.FILER_IMAGE_MODEL, verbose_name=' صوره  cover حجم الصورة المثالي  الطول:310px - العرض:1440px')),
                ('mousa_img', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mousa_img', to=settings.FILER_IMAGE_MODEL, verbose_name='صورة الجمعية في  صفحة بنذة عنا')),
                ('sheikh_img', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheikh_img', to=settings.FILER_IMAGE_MODEL, verbose_name='صورة الشيخ في  صفحة بنذة عنا ')),
            ],
            options={
                'verbose_name': 'الرئيسية',
                'verbose_name_plural': 'الرئيسية',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Fatwa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('text', models.CharField(blank=True, max_length=20000, null=True, verbose_name='نص الفتوي')),
                ('status', models.CharField(choices=[('p', 'منشور'), ('n', 'غير منشور')], default='p', max_length=1, verbose_name='حالة النشر')),
                ('file', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.file', verbose_name='الملف')),
            ],
            options={
                'verbose_name': 'الفتاوى',
                'verbose_name_plural': 'الفتاوى',
            },
        ),
        migrations.CreateModel(
            name='BookSeach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=400, verbose_name='key search')),
                ('page', models.IntegerField(validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(1)])),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.book', verbose_name='كتاب في صحيح البخاري')),
            ],
            options={
                'verbose_name': 'فهارس الكتب',
                'verbose_name_plural': 'فهارس الكتب',
            },
        ),
        migrations.CreateModel(
            name='AyatTelawa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('p', 'منشور'), ('n', 'غير منشور')], default='p', max_length=1, verbose_name='حالة النشر')),
                ('aya_end', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AyatTelawaaya_end', to='base.ayat', verbose_name='نهاية تفسير الأيات آية رقم')),
                ('aya_start', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AyatTelawaaya_start', to='base.ayat', verbose_name='بدايه تفسير الأيات من آية رقم')),
                ('sura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.sura', verbose_name='سورة')),
                ('telawa', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telawa_file', to='filer.file', verbose_name='التلاوة')),
            ],
            options={
                'verbose_name': 'القرآن الكريم',
                'verbose_name_plural': 'القرآن الكريم',
            },
        ),
        migrations.CreateModel(
            name='AyatTafsirVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, max_length=400, null=True, verbose_name='رابط الفيديو ')),
                ('text', models.CharField(blank=True, max_length=500000, null=True, verbose_name='نص تفسير الأيات')),
                ('status', models.CharField(choices=[('p', 'منشور'), ('n', 'غير منشور')], default='p', max_length=1, verbose_name='حالة النشر')),
                ('aya_end', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AyatTafsirVideoaya_end', to='base.ayat', verbose_name='نهاية تفسير الأيات آية رقم')),
                ('aya_start', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AyatTafsirVideoaya_start', to='base.ayat', verbose_name='بدايه تفسير الأيات من آية رقم')),
                ('sura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.sura', verbose_name='سورة')),
                ('video_tafsir', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_tafsir_fileAyatTafsirVideo', to='filer.file', verbose_name='ملف التفسير المرئي')),
            ],
            options={
                'verbose_name': 'التفسير المرئي',
                'verbose_name_plural': 'التفسير المرئي',
            },
        ),
        migrations.CreateModel(
            name='AyatTafsirAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=500000, null=True, verbose_name='نص تفسير الأيات')),
                ('status', models.CharField(choices=[('p', 'منشور'), ('n', 'غير منشور')], default='p', max_length=1, verbose_name='حالة النشر')),
                ('aya_end', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AyatTafsirAudioaya_end', to='base.ayat', verbose_name='نهاية تفسير الأيات آية رقم')),
                ('aya_start', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AyatTafsirAudioaya_start', to='base.ayat', verbose_name='بدايه تفسير الأيات من آية رقم')),
                ('sound_tafsir', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sound_tafsir_file', to='filer.file', verbose_name='التفسير الصوتي')),
                ('sura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.sura', verbose_name='سورة')),
            ],
            options={
                'verbose_name': 'القرآن الكريم',
                'verbose_name_plural': 'القرآن الكريم',
            },
        ),
        migrations.AddField(
            model_name='ayat',
            name='sura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.sura', verbose_name='سورة'),
        ),
        migrations.CreateModel(
            name='DailyPublish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_type', models.CharField(choices=[('aya', 'آية'), ('hadith', 'الحديث'), ('fatwa', 'فتوي'), ('part_of_book', 'فقرة من كتاب')], max_length=16, verbose_name='نوع المنشور')),
                ('content', models.CharField(blank=True, max_length=1000, null=True, verbose_name='محتوي')),
                ('day', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)], verbose_name='يوم')),
                ('status', models.CharField(choices=[('p', 'منشور'), ('n', 'غير منشور')], default='p', max_length=1, verbose_name='حالة النشر')),
                ('aya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ayat', verbose_name=' أيات')),
                ('book_in_alsaheh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.bookinalsaheh', verbose_name='الكتب/صحيح البخاري')),
                ('chapter_in_alsaheh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.chapterinalsaheh', verbose_name='الباب/صحيح البخاري')),
                ('hadith', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.hadith', verbose_name='الحديث')),
                ('sura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.sura', verbose_name='سورة')),
            ],
            options={
                'verbose_name': 'النشر اليومي',
                'verbose_name_plural': 'النشر اليومي',
                'ordering': ['day', 'publish_type'],
                'get_latest_by': ['day', 'publish_type'],
                'unique_together': {('publish_type', 'day')},
            },
        ),
    ]
