# Generated by Django 3.2.12 on 2022-03-23 10:01

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ayat',
            options={'ordering': ['sura', 'count'], 'verbose_name': ' الأيات', 'verbose_name_plural': ' الأيات'},
        ),
        migrations.AlterModelOptions(
            name='ayattafsiraudio',
            options={'verbose_name': 'التفسير الصوتي', 'verbose_name_plural': 'التفسير الصوتي'},
        ),
        migrations.AlterModelOptions(
            name='ayattelawa',
            options={'verbose_name': 'التلاوة', 'verbose_name_plural': 'التلاوة'},
        ),
        migrations.AlterField(
            model_name='dailypublish',
            name='hadith',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.hadith', verbose_name='حديث'),
        ),
        migrations.AlterField(
            model_name='dailypublish',
            name='publish_type',
            field=models.CharField(choices=[('aya', 'آية'), ('hadith', 'حديث'), ('fatwa', 'فتوي'), ('part_of_book', 'فقرة من كتاب')], max_length=16, verbose_name='نوع المنشور'),
        ),
        migrations.AlterField(
            model_name='hadith',
            name='number',
            field=models.IntegerField(verbose_name='الحديث ترتيب'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='type',
            field=models.CharField(choices=[('quran', 'القرآن الكريم'), ('hadith', 'حديث'), ('OtherScience', 'العلوم الأخري')], max_length=20, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='tafsirhadithinalsaheh',
            name='audio_tafsir',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_hadith_file', to='filer.file', verbose_name='التفسير الصوتي'),
        ),
        migrations.AlterField(
            model_name='tafsirhadithinalsaheh',
            name='hadith',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.hadith', verbose_name='حديث'),
        ),
        migrations.AlterUniqueTogether(
            name='dailypublish',
            unique_together={('publish_type', 'day', 'status')},
        ),
    ]
