# Generated by Django 3.2.12 on 2022-03-24 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220323_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ayattafsirvideo',
            options={'ordering': ['sura', 'aya_start'], 'verbose_name': 'التفسير المرئي', 'verbose_name_plural': 'التفسير المرئي'},
        ),
        migrations.AlterModelOptions(
            name='sura',
            options={'ordering': ['number'], 'verbose_name': 'تفسير القرآن والتلاوة', 'verbose_name_plural': 'السورة'},
        ),
    ]
