# Generated by Django 3.2.12 on 2022-03-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220324_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinalsaheh',
            name='name',
            field=models.CharField(max_length=500, verbose_name='اسم الكتاب'),
        ),
        migrations.AlterField(
            model_name='bookinalsaheh',
            name='name_without_tashkil',
            field=models.CharField(max_length=500, verbose_name='without tashkel العنوان'),
        ),
        migrations.AlterField(
            model_name='callus',
            name='name',
            field=models.CharField(max_length=200, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='chapterinalsaheh',
            name='name',
            field=models.CharField(max_length=500, verbose_name='أسم الباب'),
        ),
        migrations.AlterField(
            model_name='chapterinalsaheh',
            name='name_without_tashkil',
            field=models.CharField(max_length=500, verbose_name='without tashkel العنوان'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='البريد الالكتروني'),
        ),
    ]
