# Generated by Django 3.2.12 on 2022-03-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220327_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط يوتيوب'),
        ),
    ]
