# Generated by Django 3.2.12 on 2022-04-06 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220330_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='العنوان')),
            ],
            options={
                'verbose_name': 'أنواع المجالس',
                'verbose_name_plural': 'أنواع المجالس',
            },
        ),
        migrations.DeleteModel(
            name='PrayTime',
        ),
        migrations.AddField(
            model_name='sessions',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.sessionscategory'),
        ),
    ]
