# Generated by Django 3.2.12 on 2022-04-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220406_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionscategory',
            name='type',
            field=models.CharField(choices=[('quran', 'القرآن الكريم'), ('hadith', 'حديث'), ('OtherScience', 'العلوم الأخري')], default='quran', max_length=20, verbose_name='نوع'),
            preserve_default=False,
        ),
    ]
