# Generated by Django 3.2.12 on 2022-04-11 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('base', '0008_sessionscategory_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ayattafsiraudio',
            options={'verbose_name': 'التفسير الصوتى', 'verbose_name_plural': 'التفسير الصوتى'},
        ),
        migrations.AlterModelOptions(
            name='ayattafsirvideo',
            options={'ordering': ['sura', 'aya_start'], 'verbose_name': 'التفسير المرئى', 'verbose_name_plural': 'التفسير المرئى'},
        ),
        migrations.AlterModelOptions(
            name='bookinalsaheh',
            options={'verbose_name': 'الكتب/صحيح البخارى', 'verbose_name_plural': 'الكتب/صحيح البخارى'},
        ),
        migrations.AlterModelOptions(
            name='chapterinalsaheh',
            options={'verbose_name': 'الباب/صحيح البخارى', 'verbose_name_plural': 'الباب/صحيح البخارى'},
        ),
        migrations.AlterModelOptions(
            name='dailypublish',
            options={'get_latest_by': ['day', 'publish_type'], 'ordering': ['day', 'publish_type'], 'verbose_name': 'النشر اليومى', 'verbose_name_plural': 'النشر اليومى'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'البريد الالكترونى', 'verbose_name_plural': 'البريد الالكترونى'},
        ),
        migrations.AlterModelOptions(
            name='hadith',
            options={'ordering': ['number'], 'verbose_name': 'الحديث فى صحيح البخارى', 'verbose_name_plural': 'الحديث فى صحيح البخارى'},
        ),
        migrations.AlterModelOptions(
            name='otherscience',
            options={'ordering': ['subject', 'title'], 'verbose_name': 'العلوم الأخرى', 'verbose_name_plural': 'العلوم الأخرى'},
        ),
        migrations.AlterModelOptions(
            name='othersciencesubject',
            options={'ordering': ['subjects'], 'verbose_name': 'مواضيع العلوم الأخرى', 'verbose_name_plural': 'مواضيع العلوم الأخرى'},
        ),
        migrations.AlterModelOptions(
            name='sessions',
            options={'ordering': ['type', 'category'], 'verbose_name': 'المجالس', 'verbose_name_plural': 'مجالس'},
        ),
        migrations.AlterModelOptions(
            name='sessionscategory',
            options={'ordering': ['type', 'name'], 'verbose_name': 'أنواع المجالس', 'verbose_name_plural': 'أنواع المجالس'},
        ),
        migrations.AlterField(
            model_name='ayattafsiraudio',
            name='sound_tafsir',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sound_tafsir_file', to='filer.file', verbose_name='التفسير الصوتى'),
        ),
        migrations.AlterField(
            model_name='ayattafsirvideo',
            name='video_tafsir',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='video_tafsir_fileAyatTafsirVideo', to='filer.file', verbose_name='ملف التفسير المرئى'),
        ),
        migrations.AlterField(
            model_name='bookseach',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.book', verbose_name='كتاب فى صحيح البخارى'),
        ),
        migrations.AlterField(
            model_name='callus',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='البريد الالكترونى'),
        ),
        migrations.AlterField(
            model_name='chapterinalsaheh',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.bookinalsaheh', verbose_name='كتاب فى صحيح البخارى'),
        ),
        migrations.AlterField(
            model_name='dailypublish',
            name='book_in_alsaheh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.bookinalsaheh', verbose_name='الكتب/صحيح البخارى'),
        ),
        migrations.AlterField(
            model_name='dailypublish',
            name='chapter_in_alsaheh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.chapterinalsaheh', verbose_name='الباب/صحيح البخارى'),
        ),
        migrations.AlterField(
            model_name='dailypublish',
            name='content',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='محتوى'),
        ),
        migrations.AlterField(
            model_name='dailypublish',
            name='publish_type',
            field=models.CharField(choices=[('aya', 'آية'), ('hadith', 'حديث'), ('fatwa', 'فتوى'), ('part_of_book', 'فقرة من كتاب')], max_length=16, verbose_name='نوع المنشور'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='البريد الالكترونى'),
        ),
        migrations.AlterField(
            model_name='fatwa',
            name='text',
            field=models.CharField(blank=True, max_length=20000, null=True, verbose_name='نص الفتوى'),
        ),
        migrations.AlterField(
            model_name='general_information',
            name='cover_page',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cover_page', to=settings.FILER_IMAGE_MODEL, verbose_name=' صوره  cover حجم الصورة المثالى  الطول:310px - العرض:1440px'),
        ),
        migrations.AlterField(
            model_name='general_information',
            name='mousa_img',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mousa_img', to=settings.FILER_IMAGE_MODEL, verbose_name='صورة الجمعية فى  صفحة بنذة عنا'),
        ),
        migrations.AlterField(
            model_name='general_information',
            name='sheikh_img',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sheikh_img', to=settings.FILER_IMAGE_MODEL, verbose_name='صورة الشيخ فى  صفحة بنذة عنا '),
        ),
        migrations.AlterField(
            model_name='hadith',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.bookinalsaheh', verbose_name='كتاب فى صحيح البخارى'),
        ),
        migrations.AlterField(
            model_name='hadith',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.chapterinalsaheh', verbose_name='الباب/صحيح البخارى'),
        ),
        migrations.AlterField(
            model_name='otherscience',
            name='file',
            field=filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.PROTECT, to='filer.file', verbose_name='محتوى'),
        ),
        migrations.AlterField(
            model_name='otherscience',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.othersciencesubject', verbose_name='مواضيع العلوم الأخرى'),
        ),
        migrations.AlterField(
            model_name='othersciencesubject',
            name='file_type',
            field=models.CharField(choices=[('video', 'فيديو'), ('audio', 'ملف صوتى')], max_length=12, verbose_name='نوع الملف'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.sessionscategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='file',
            field=filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.PROTECT, to='filer.file', verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='type',
            field=models.CharField(choices=[('quran', 'القرآن الكريم'), ('hadith', 'حديث'), ('OtherScience', 'العلوم الأخرى')], max_length=20, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='sessionscategory',
            name='type',
            field=models.CharField(choices=[('quran', 'القرآن الكريم'), ('hadith', 'حديث'), ('OtherScience', 'العلوم الأخرى')], max_length=20, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='tafsirhadithinalsaheh',
            name='audio_tafsir',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audio_hadith_file', to='filer.file', verbose_name='التفسير الصوتى'),
        ),
        migrations.AlterField(
            model_name='tafsirhadithinalsaheh',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.bookinalsaheh', verbose_name='كتاب فى صحيح البخارى'),
        ),
        migrations.AlterField(
            model_name='tafsirhadithinalsaheh',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.chapterinalsaheh', verbose_name='الباب/صحيح البخارى'),
        ),
        migrations.AlterField(
            model_name='tafsirhadithinalsaheh',
            name='video_tafsir',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TafsirHadithInAlSahehvideo_tafsir_file', to='filer.file', verbose_name='التفسير المرئى'),
        ),
    ]
