# Generated by Django 3.2.12 on 2022-04-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20220411_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinalsaheh',
            options={'ordering': ['id'], 'verbose_name': 'الكتب/صحيح البخارى', 'verbose_name_plural': 'الكتب/صحيح البخارى'},
        ),
        migrations.AlterModelOptions(
            name='chapterinalsaheh',
            options={'ordering': ['book', 'id'], 'verbose_name': 'الباب/صحيح البخارى', 'verbose_name_plural': 'الباب/صحيح البخارى'},
        ),
        migrations.AddField(
            model_name='phonenumbers',
            name='phone_number_type',
            field=models.CharField(choices=[('telephon', 'telephon'), ('mobile', 'mobile'), ('fax', 'fax')], default='telephon', max_length=20, verbose_name='نوع'),
            preserve_default=False,
        ),
    ]
