# Generated by Django 3.2.12 on 2022-04-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20220419_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumbers',
            name='phone_number_type',
            field=models.CharField(choices=[('telephon', 'تيليفون'), ('mobile', 'موبايل'), ('fax', 'فاكس')], max_length=20, verbose_name='نوع'),
        ),
    ]
