# Generated by Django 3.2.12 on 2022-04-21 09:39

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_phonenumbers_phone_number_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessions',
            options={'ordering': ['order', 'type', 'category', 'id'], 'verbose_name': 'المجالس', 'verbose_name_plural': 'مجالس'},
        ),
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('reg_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='sessions',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='ترتيب'),
        ),
    ]
