# Generated by Django 3.2.12 on 2022-04-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_book_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessions',
            options={'ordering': ['type', 'category', 'id'], 'verbose_name': 'المجالس', 'verbose_name_plural': 'مجالس'},
        ),
        migrations.AlterModelOptions(
            name='sessionscategory',
            options={'ordering': ['order', 'type', 'name'], 'verbose_name': 'أنواع المجالس', 'verbose_name_plural': 'أنواع المجالس'},
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='order',
        ),
        migrations.AddField(
            model_name='sessionscategory',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='ترتيب'),
        ),
    ]
