# Generated by Django 3.2.12 on 2022-05-11 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('base', '0014_auto_20220421_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('type', 'title'), 'verbose_name': 'الكتب والمقالات', 'verbose_name_plural': 'الكتب والمقالات'},
        ),
        migrations.AddField(
            model_name='relatedsites',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RelatedSites_image', to=settings.FILER_IMAGE_MODEL, verbose_name=' صوره  cover حجم الصورة المثالى  الطول:310px - العرض:1440px'),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('book', 'كتاب'), ('artical', 'المقال')], max_length=10, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='hadith',
            name='number',
            field=models.IntegerField(verbose_name='الحديث الشريف ترتيب'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='type',
            field=models.CharField(choices=[('quran', 'القرآن الكريم'), ('hadith', 'الحديث الشريف'), ('OtherScience', 'العلوم الأخرى')], max_length=20, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='sessionscategory',
            name='type',
            field=models.CharField(choices=[('quran', 'القرآن الكريم'), ('hadith', 'الحديث الشريف'), ('OtherScience', 'العلوم الأخرى')], max_length=20, verbose_name='نوع'),
        ),
    ]
