# Generated by Django 3.2.12 on 2022-05-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20220511_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessions',
            options={'ordering': ['type', 'category', 'file__folder', 'title', 'id'], 'verbose_name': 'المجالس', 'verbose_name_plural': 'مجالس'},
        ),
        migrations.AlterField(
            model_name='general_information',
            name='facebook_link',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الفيسبوك'),
        ),
        migrations.AlterField(
            model_name='general_information',
            name='instagram_link',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الانسجرام'),
        ),
        migrations.AlterField(
            model_name='general_information',
            name='twitter_link',
            field=models.URLField(blank=True, null=True, verbose_name='رابط تويتر'),
        ),
        migrations.AlterField(
            model_name='general_information',
            name='youtube_link',
            field=models.URLField(blank=True, null=True, verbose_name='رابط يوتيوب'),
        ),
    ]
