# Generated by Django 3.2.12 on 2022-05-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20220515_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_information',
            name='app_store_link',
            field=models.URLField(blank=True, null=True, verbose_name='رابط تطبيق IOS'),
        ),
        migrations.AddField(
            model_name='general_information',
            name='google_play_link',
            field=models.URLField(blank=True, null=True, verbose_name='رابط تطبيق Android'),
        ),
    ]
