# Generated by Django 3.2.12 on 2022-09-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20220519_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='othersciencesubject',
            options={'ordering': ['-subjects'], 'verbose_name': 'مواضيع العلوم الأخرى', 'verbose_name_plural': 'مواضيع العلوم الأخرى'},
        ),
        migrations.AddField(
            model_name='othersciencesubject',
            name='order',
            field=models.IntegerField(null=True, verbose_name='order'),
        ),
    ]
