# Generated by Django 3.2.12 on 2022-09-07 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('base', '0018_auto_20220906_0833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinalsaheh',
            options={'ordering': ['id'], 'verbose_name': 'AlHadith/AlSaheh/books', 'verbose_name_plural': 'AlHadith/AlSaheh/books'},
        ),
        migrations.AlterModelOptions(
            name='hadith',
            options={'ordering': ['number'], 'verbose_name': 'hadith in Al Saheh', 'verbose_name_plural': 'hadith in Al Saheh'},
        ),
        migrations.AlterModelOptions(
            name='phonenumbers',
            options={'verbose_name': 'phone numbers', 'verbose_name_plural': 'phone numbers'},
        ),
        migrations.AlterField(
            model_name='bookinalsaheh',
            name='name',
            field=models.CharField(max_length=500, verbose_name='book name'),
        ),
        migrations.AlterField(
            model_name='chapterinalsaheh',
            name='name',
            field=models.CharField(max_length=500, verbose_name='chapter name'),
        ),
        migrations.AlterField(
            model_name='dailypublish',
            name='book_in_alsaheh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.bookinalsaheh', verbose_name='AlHadith/AlSaheh/books'),
        ),
        migrations.AlterField(
            model_name='general_information',
            name='cover_page',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cover_page', to=settings.FILER_IMAGE_MODEL, verbose_name='perfect cover page size height:310px - width:1440px'),
        ),
        migrations.AlterField(
            model_name='relatedsites',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RelatedSites_image', to=settings.FILER_IMAGE_MODEL, verbose_name='perfect cover page size height:310px - width:1440px'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='type',
            field=models.CharField(choices=[('quran', 'القرآن الكريم'), ('hadith', 'الحديث الشريف'), ('OtherScience', 'العلوم الأخرى'), ('pillars', 'الإسلا م و اركانه')], max_length=20, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رابط يوتيوب'),
        ),
        migrations.AlterField(
            model_name='sessionscategory',
            name='type',
            field=models.CharField(choices=[('quran', 'القرآن الكريم'), ('hadith', 'الحديث الشريف'), ('OtherScience', 'العلوم الأخرى'), ('pillars', 'الإسلا م و اركانه')], max_length=20, verbose_name='نوع'),
        ),
    ]
