# Generated by Django 3.2.12 on 2022-09-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20220907_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadith',
            name='text_without_tashkil',
            field=models.TextField(max_length=100000, verbose_name='النص بدون تشكيل'),
        ),
    ]
