# Generated by Django 3.2.12 on 2022-09-17 07:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_hadith_text_without_tashkil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadith',
            name='text_without_tashkil',
            field=ckeditor.fields.RichTextField(max_length=100000, verbose_name='النص بدون تشكيل'),
        ),
    ]
