# Generated by Django 3.2.12 on 2023-06-19 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_hadith_text_without_tashkil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookseach',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chapter', to='base.book', verbose_name='كتاب فى صحيح البخارى'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='type',
            field=models.CharField(choices=[('quran', 'القرآن الكريم'), ('hadith', 'الحديث الشريف'), ('OtherScience', 'العلوم الأخرى'), ('pillars', 'الإسلا م و أركانه')], max_length=20, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='sessionscategory',
            name='type',
            field=models.CharField(choices=[('quran', 'القرآن الكريم'), ('hadith', 'الحديث الشريف'), ('OtherScience', 'العلوم الأخرى'), ('pillars', 'الإسلا م و أركانه')], max_length=20, verbose_name='نوع'),
        ),
    ]
