# Generated by Django 3.2.12 on 2023-06-22 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20230619_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailypublish',
            options={'get_latest_by': ['display_date', 'publish_type'], 'ordering': ['display_date', 'publish_type'], 'verbose_name': 'النشر اليومى', 'verbose_name_plural': 'النشر اليومى'},
        ),
        migrations.AddField(
            model_name='dailypublish',
            name='display_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='display date'),
        ),
        migrations.AlterUniqueTogether(
            name='dailypublish',
            unique_together={('publish_type', 'display_date', 'day', 'status')},
        ),
    ]
