# Generated by Django 3.2.12 on 2023-07-07 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20230707_0847'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailypublish',
            unique_together={('publish_type', 'display_date', 'status')},
        ),
        migrations.RemoveField(
            model_name='dailypublish',
            name='day',
        ),
    ]
